#!/usr/bin/env bash
#
# drop and restore database from generated SQL

rootdir="$(cd "${0%/*}/../." && pwd -P)"
datadir="${rootdir}/data"

if [[ -z "${PGUSER}" ]] || [[ -z "${PGDATABASE}" ]]; then
  echo "Please set the PGUSER and PGDATABASE environment variables." >&2
  echo "See: env" >&2
  exit 1
fi

${rootdir}/tools/setup || exit $?
tools/mksql | psql --user=${PGUSER} ${PGDATABASE} || exit $?
