#!/usr/bin/env bash
#
# drop and recreate a postgresql user and database
#

export PGUSER="${USER}"

database="dvdrental"
user="dvdrental"

dropdb "${database}" --if-exists || exit $?
dropuser "${user}" --if-exists || exit $?

createuser "${user}" --role=pg_read_server_files
createdb "${database}" --owner="${user}" --lc-collate=C --encoding=UTF-8
